apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: nginx-service-b
  namespace: my-apps
spec:
  podSelector:
    matchLabels:
      app: app-2
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: nginx-service-b.my-apps.svc.cluster.local
