apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: nginx-service-a
  namespace: my-apps
spec:
  podSelector:
    matchLabels:
      app: app-1
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: nginx-service-a.my-apps.svc.cluster.local
